### ISSUE TITLE
`_get_reset_seconds_` causes fatal crash

### ISSUE THREAD

**Issue by pekasen** [Leibniz-HBI/spiderexpress-tiktok#2]
```pytb
Traceback (most recent call last):
  File ".../bin/spiderexpress", line 8, in <module>
    sys.exit(cli())
             ~~~^^
  File ".../lib/python3.13/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File ".../lib/python3.13/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File ".../lib/python3.13/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File ".../lib/python3.13/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.13/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File ".../lib/python3.13/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File ".../lib/python3.13/site-packages/spiderexpress/cli.py", line 53, in start
    ctx.obj.start(config)
    ~~~~~~~~~~~~~^^^^^^^^
  File ".../lib/python3.13/site-packages/transitions/core.py", line 406, in trigger
    return self.machine._process(func)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File ".../lib/python3.13/site-packages/transitions/core.py", line 1251, in _process
    self._transition_queue[0]()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File ".../lib/python3.13/site-packages/transitions/core.py", line 420, in _trigger
    self._process(event_data)
    ~~~~~~~~~~~~~^^^^^^^^^^^^
  File ".../lib/python3.13/site-packages/transitions/core.py", line 443, in _process
    if trans.execute(event_data):
       ~~~~~~~~~~~~~^^^^^^^^^^^^
  File ".../lib/python3.13/site-packages/transitions/core.py", line 278, in execute
    self._change_state(event_data)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File ".../lib/python3.13/site-packages/transitions/core.py", line 289, in _change_state
    dest.enter(event_data)
    ~~~~~~~~~~^^^^^^^^^^^^
  File ".../lib/python3.13/site-packages/transitions/core.py", line 130, in enter
    event_data.machine.callbacks(self.on_enter, event_data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.13/site-packages/transitions/core.py", line 1174, in callbacks
    self.callback(func, event_data)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.13/site-packages/transitions/core.py", line 1195, in callback
    func(*event_data.args, **event_data.kwargs)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.13/site-packages/spiderexpress/spider.py", line 439, in gather_node_data
    self._dispatch_connector_for_node_(task, task.connector)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.13/site-packages/spiderexpress/spider.py", line 559, in _dispatch_connector_for_node_
    raw_edges, nodes = connector([node.node_id])
                       ~~~~~~~~~^^^^^^^^^^^^^^^^
  File ".../lib/python3.13/site-packages/spiderexpress_tiktok/spiderexpress_tiktok.py", line 88, in wrapper
    return func(*args, **kwargs)
  File ".../lib/python3.13/site-packages/spiderexpress_tiktok/spiderexpress_tiktok.py", line 142, in _followings_
    _users_info_(handle=handle, token=token)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.13/site-packages/spiderexpress_tiktok/spiderexpress_tiktok.py", line 79, in wrapper
    seconds_until_reset = _get_reset_seconds_(reset_date)
  File ".../lib/python3.13/site-packages/spiderexpress_tiktok/spiderexpress_tiktok.py", line 55, in _get_reset_seconds_
    return (reset_date - datetime.datetime.now()).total_seconds()
            ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by pekasen** [comment]
Fixed in #3.
